### ISSUE TITLE
Destroy failed when enable both vulkan backend and api validation

### ISSUE THREAD

**Issue by damnkk** [NVIDIA-RTX/NRIFramework#3]
In the Initialize function,if I set the graphic API to Vulkan ,enable APIValidation, and call InitUI(...) at the end of the function, I will get the fatal error  "DestroyDebugAllocator() failed: allocatedSize is not 0." because of a small piece of leaked memory when the program is destroyed. "
![image](https://github.com/NVIDIAGameWorks/NRIFramework/assets/89560356/5b3854b6-49fe-47de-ac64-4b38e0ea4770)
I obtained the allocation number and size of these leaked memories 
![image](https://github.com/NVIDIAGameWorks/NRIFramework/assets/89560356/369d4454-98e1-4b56-b3d7-36f502eac9aa)
After rigorous analysis, I can absolutely guarantee that these memories do not come from undestructed vulkan objects.
I hope someone can help me analyze what I did wrong, or is there a hidden bug in the framework? (Unlikely)
Any help is greatly appreciated:)

|backend |           enableAPIValidation   |          leak |
|---------|--------------------------------|-------------|
|VULKAN|&#10004;|&#10004;|
|VULKAN|x|x|
|D3D12|&#10004;|x|
|D3D12|x|x|

**Comment by dzhdanNV** [comment]
Hi! The leak most likely comes from the VK validation layer. Please, update to the VK SDK to v1.3.283 or newer and try again. I will update NRI and related projects to the latest today. I can't reproduce this issue anymore.

**Comment by damnkk** [comment]
> Hi! The leak most likely comes from the VK validation layer. Please, update to the VK SDK to v1.3.283 or newer and try again. I will update NRI and related projects to the latest today. I can't reproduce this issue anymore.

thank you, the error not come out after I update the vulkan SDK :-)
