### ISSUE TITLE
Cannot compile because of swizzling

### ISSUE THREAD

**Issue by maaxxaam** [NVIDIA-RTX/NRIFramework#6]
Trying to compile the repo (both as a CMake dependency and through the build script) on my Linux machine results in the following error:
```
[ 94%] Building CXX object CMakeFiles/NRIFramework.dir/Source/Utils.cpp.o
NRIFramework/Source/Utils.cpp: In function 'void DecomposeAffine(const float4x4&, float3&, float4&, float3&)':
NRIFramework/Source/Utils.cpp:653:34: error: request for member 'xyz' in 'transform.float4x4::<anonymous>.float4x4::<unnamed struct>::col3', which is of non-class type 'const v4f' {aka 'const __m128'}
  653 |     translation = transform.col3.xyz;
      |                                  ^~~
```
Editing the line in question to avoid the swizzling (in a hacky way) makes it work without any issues:
```diff
 void DecomposeAffine(const float4x4& transform, float3& translatio
n, float4& rotation, float3& scale) {
-    translation = transform.col3.xyz;
+    translation = (float3)transform.col3;

     float3 col0 = transform.col0;
     float3 col1 = transform.col1;
```
Is there a better way to resolve this error?

**Comment by dzhdanNV** [comment]
He-he. In the depths of `MathLib` `float4` is (because of problems with GNUC):
```c++
union float4x4 {
#if defined(__GNUC__)
    struct {
        v4f col0;
        v4f col1;
        v4f col2;
        v4f col3;
    };
#else
    struct {
        float4 col0;
        float4 col1;
        float4 col2;
        float4 col3;
    };
#endif
```
So, yeah, `.xyz` becomes unavailable. You can use just:
```
translation = transform.col3;
```
Looks simpler.

**Comment by maaxxaam** [comment]
> You can use just:
> 
> ```
> translation = transform.col3;
> ```
> 
> Looks simpler.

Thank you for the quick reply. In the opening message I went for the C-style cast to make the `float4 -> float3` conversion more explicit as we're trying to intentionally lose data (the vector's 4th component). Making this impicit is indeed simpler but can be easily misunderstood as an error on later code revisions.

**Comment by dzhdanNV** [comment]
OK. Sounds reasonable.

**Comment by dzhdanNV** [comment]
Thanks for the fix. Closing?

**Comment by maaxxaam** [comment]
It was a nice experience fixing this, thank you. Closing as completed.
